### ISSUE TITLE
Win Condition

### ISSUE THREAD

**Issue by TravisWhitehead** [OSU-CS361-W17/group7_project1#13]
**Story:** As a player, I want the game to end when all ships on one side are sunk, so that the game can have a winning condition.

**Comment by ghost** [comment]
We can probably handle this easily by checking when the length of our arrayLists playerHits or computerHits is 16 (the number of hits to sink all ships).

Maybe another method in main that's called at the end of the fireAt() method that just checks the length of these arrayLists?

**Comment by TravisWhitehead** [comment]
Decided to scrap this story.
